from __future__ import annotations

from typing import Protocol

from workbalancer.domain.models import AgentJob, AgentWebhookPayload, Project


class ProjectRepositoryPort(Protocol):
    async def list_projects(self) -> list[Project]: ...
    async def get_by_id(self, project_id: int) -> Project | None: ...
    async def get_by_url(self, repository_url: str) -> Project | None: ...
    async def create(self, name: str, repository_url: str, ref: str) -> Project: ...


class ChatContextRepositoryPort(Protocol):
    async def get_active_project_id(self, chat_id: int) -> int | None: ...
    async def set_active_project(self, chat_id: int, project_id: int | None) -> None: ...


class AgentJobRepositoryPort(Protocol):
    async def create_pending(
        self,
        project_id: int,
        telegram_chat_id: int,
        telegram_user_id: int,
        prompt_preview: str,
    ) -> AgentJob: ...
    async def update_from_launch(self, job_id: int, cursor_agent_id: str, status: str, agent_url: str | None) -> None: ...
    async def update_from_webhook(
        self, cursor_agent_id: str, payload: AgentWebhookPayload, webhook_delivery_id: str | None
    ) -> AgentJob | None: ...
    async def get_by_cursor_id(self, cursor_agent_id: str) -> AgentJob | None: ...
    async def get_by_id(self, job_id: int) -> AgentJob | None: ...
    async def count_active_for_user(self, telegram_user_id: int) -> int: ...
    async def list_stale_running(self, older_than_seconds: int) -> list[AgentJob]: ...
    async def mark_launch_failed(self, job_id: int, error_message: str) -> None: ...


class AuditRepositoryPort(Protocol):
    async def log(self, telegram_user_id: int, action: str, details: dict) -> None: ...


class CursorCloudPort(Protocol):
    async def launch_agent(
        self,
        prompt_text: str,
        repository_url: str,
        ref: str,
        webhook_url: str,
        webhook_secret: str,
        auto_create_pr: bool,
    ) -> dict: ...
    async def get_agent(self, agent_id: str) -> dict: ...
    async def add_followup(self, agent_id: str, prompt_text: str) -> dict: ...
    async def stop_agent(self, agent_id: str) -> None: ...
    async def list_repositories(self) -> list[dict]: ...


class RedisPort(Protocol):
    async def try_acquire_webhook(self, webhook_id: str | None, agent_id: str, status: str) -> bool: ...
    async def set_pending_task(self, chat_id: int, project_id: int, prompt: str) -> None: ...
    async def get_pending_task(self, chat_id: int) -> tuple[int, str] | None: ...
    async def clear_pending_task(self, chat_id: int) -> None: ...
    async def get_cached_repositories(self) -> list[dict] | None: ...
    async def set_cached_repositories(self, repos: list[dict], ttl_seconds: int) -> None: ...
    async def try_notify_terminal_once(self, cursor_agent_id: str) -> bool: ...
